# the first server block will serve as default for every ip:port combination
# all filenames need to be absolute paths, are relative to the directory where the server is started
server {
	listen 8081; # listen on port 80, on every available ip address
	server_name fmol.com helloworld.be; # server name (optional or multiple space separated) == supports absolute and '*' wildcard server names
	location / { # (optional) every uri that starts with / will be handled by this block (longest prefix match)
		allow GET POST { # (optional) allow only GET and POST requests only on this location block 
			return 405; # return 405 status code if request is not allowed (redirect also possible)
		}
		root /data/www; # (optional) root directory for the files (uri will be appended to this path)
	}
	location /images/ {
		root /data;
	}
	# works with longest prefix match for uri (if /images/ is not found, / will be used)
	root /data/www; # (optional )root directory for the files (fallback in case no location block is matched), default is /
	#empty location block will also use root directive in server block
	max_size 32; # (optional ) maximum size of the request body in megabytes (default is 1000000)
	index /data/www/index.html; # (optional) possible values are a filename, auto (generates list of files), off (disables directory listing), default is off
	error_page 404 /data/errorPages/custom_404.html; # (optional) define custom error page for 404 error = if not found, falls back to error_page directive in parent block
	error_page 400 /data/errorPages/custom_400.html;
}

server {
	listen 8080; # listen on port 8080
	server_name area.com; # server name
	location / {
		root /data/www; # root directory for the files (uri will be appended to this path)
		index auto;
	}

	location /reroute { # location block for /route
		return 301 /; # redirect to /route
		#return 302 /; # redirect to /route with 302 status code
	}

	location /*/.py { #location blocks with file extensions will be used for requesting cgi scripts
		root /data/cgi-bin; 
	}
}

server {
	listen 127.0.0.1:8080; # listen on port 8080 and ip
	server_name www.42web.com 42web.com; 
	location / {
		root /data/www/42web;
		index /data/www/42web/index.html;
	}
}