/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   SessionIdGenerator.hpp                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: fmol <fmol@student.s19.be>                 +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/04/16 16:02:58 by fmol              #+#    #+#             */
/*   Updated: 2025/04/17 09:29:24 by fmol             ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef SESSIONIDGENERATOR_HPP
#define SESSIONIDGENERATOR_HPP

#include <string>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <set>
#include <vector>

/**
 * @class SessionIdGenerator
 * @brief Class to generate session IDs.
 * @details This class generates random hexadecimal session IDs with entropy from /dev/urandom.
 * It keeps a buffer to reduce the number of reads from /dev/urandom.
 * The buffer is refreshed when it runs out of data.
 */
class SessionIdGenerator
{
public:
	/**
	 * @brief Constructor
	 * @param bufferSize Size of the buffer to read from /dev/urandom.
	 * @details allocates a buffer of the specified size.
	 * @throws std::runtime_error if it cannot allocate memory for the buffer.
	 * @throws std::runtime_error if it cannot read from /dev/urandom.
	 */
	SessionIdGenerator(size_t bufferSize = 128);
	~SessionIdGenerator();

	/**
	 * @brief Generates random bytes.
	 * @details This function fills the provided buffer from the internal buffer.
	 * If the internal buffer is out of data, it will be refreshed from /dev/urandom.
	 * @param dest Buffer to store the generated bytes.
	 * @param size Size of the buffer.
	 * @return True if successful, false otherwise.
	 */
	bool getRandomBytes(unsigned char *dest, size_t size);

	/**
	 * @brief Generates a session ID.
	 * @param length Length of the session ID to generate.
	 * @return A session ID in hexadecimal format.
	 * @throws std::runtime_error if it cannot acquire enough random bytes.
	 */
	std::string generateSessionId(size_t length = 16);

	/**
	 * @brief Generates a unique session ID.
	 * @param existingIds Set of existing session IDs to check against.
	 * @param length Length of the session ID to generate.
	 * @return A unique session ID.
	 * @details calls generateSessionId() until a unique ID is generated.
	 * Therefore, it can throw std::runtime_error if it cannot acquire enough random bytes.
	 * @throws std::runtime_error if it cannot acquire enough random bytes.
	 */
	std::string generateUniqueSessionId(std::set<std::string> &existingIds, size_t length = 16);

private:
	/**
	 * @brief Refreshes the internal buffer by reading from /dev/urandom.
	 * @return True if successful, false otherwise.
	 */
	bool refreshBuffer();

	const size_t _bufferSize;
	unsigned char *_buffer;
	size_t _bufferIndex;
};

#endif // SESSIONIDGENERATOR_HPP